site_name: Meta Marble
site_url: https://www.marble.blue/
site_description: Spatial Data Directory
site_author: Geoid
lang: en

repo_name: 'GitHub'
repo_url: https://github.com/geoid-org/marble/
edit_uri_template: 'docs/{path}'

dev_addr: 127.0.0.1:8888

theme:
  name: material
  locale: en
  palette:
    scheme: geoid
  logo: assets/image/logo_light.png
  favicon: assets/favicon/favicon.ico
  # features:
  #   - navigation.tabs

extra_css:
  - assets/style/extra.css
extra_javascript:
  - assets/script/extra.js
extra_templates:

extra:
  generator: false
  analytics:
    provider: google
    property: G-Y533KG4MT4
  social:
    - icon: fontawesome/solid/globe 
      link: https://www.geoid.org
    - icon: fontawesome/brands/github 
      link: https://github.com/geoid-org
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/geoid-org
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/geoid_org
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/geoid.org

copyright: Copyright &copy; 2023 Geoid

hide:
  - footer

# Page tree
nav:
  - Introduction: 'index.md'
  - Resources:
      - 'Glossary': 'resources/glossary.md'
      - 'Links': 'resources/links.md'
  - About:
      - 'Authors': 'about/authors.md'
  - Legal Information:
      - 'License': 'legal/license.md'
      - 'Privacy Policy': 'legal/privacy_policy.md'
      - 'Disclaimer': 'legal/disclaimer.md'
